-- AlterTable
ALTER TABLE "cash_register"
ALTER COLUMN "closingBalance" DROP DEFAULT,
ALTER COLUMN "closingBalance" DROP NOT NULL,
ADD COLUMN "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "closedAt" TIMESTAMP(3);
